### ISSUE TITLE
Could not find dbt profile for when env_var is used

### ISSUE THREAD

**Issue by MurugR** [innoverio/vscode-dbt-power-user#130]
Hi, 

Getting this error with versions greater than 0.7.0. Error goes away when I downgrade to 0.7.0. Looks like the use of jinja stopped being recognized after 0.7.0?

Could not find dbt profile for '{{ env_var('ENV_DBT_PROFILE') }}' in file:///c%3A/Users/MurugR/.dbt. Did you create a dbt profile?

Also getting this when I run a model manually. 
![image](https://user-images.githubusercontent.com/80878454/192787247-980e8b3e-31fb-4bf9-b7df-cfdfb2841cc6.png)

Thanks and regards,
Rama

**Comment by samprohaska** [comment]
I'm seeing a similar issue after upgrading the extension. I get the same error when using the "Compile dbt Preview" and "Execute dbt SQL" commands (running the model and tests work without issue).

Oddly enough, I still get the same error after hardcoding a valid target name into my project's `profiles.yml` file (`name1` vs calling an env variable via dbt's `{{  env_var('DBT_DEV_ENV')  }}`. `DBT_DEV_ENV` is a zsh environment variable, set via `~/.zshrc`.

```
"message": "Runtime Error
  The profile '{my-bigquery-profile}' does not have a target named '{{  env_var('DBT_DEV_ENV')  }}'. The valid target names for this profile are:
   - {name1}
   - {name2}
   - {name3}",
  "data": "Traceback (most recent call last):
  File \"<string>\", line 21, in <module>
  File \"/Users/{username}/dev/py-venvs/dbtenv/lib/python3.10/site-packages/dbt_osmosis/core/osmosis.py\", line 187, in __init__
    self.project, self.profile = RuntimeConfig.collect_parts(args)
  File \"/Users/{username}/dev/py-venvs/dbtenv/lib/python3.10/site-packages/dbt/config/runtime.py\", line 202, in collect_parts
    profile = cls._get_rendered_profile(args, profile_renderer, profile_name)
  File \"/Users/{username}/dev/py-venvs/dbtenv/lib/python3.10/site-packages/dbt/config/runtime.py\", line 187, in _get_rendered_profile
    return Profile.render_from_args(args, profile_renderer, profile_name)
  File \"/Users/{username}/dev/py-venvs/dbtenv/lib/python3.10/site-packages/dbt/config/profile.py\", line 428, in render_from_args
    return cls.from_raw_profiles(
  File \"/Users/{username}/dev/py-venvs/dbtenv/lib/python3.10/site-packages/dbt/config/profile.py\", line 394, in from_raw_profiles
    return cls.from_raw_profile_info(
  File \"/Users/{username}/dev/py-venvs/dbtenv/lib/python3.10/site-packages/dbt/config/profile.py\", line 338, in from_raw_profile_info
    target_name, profile_data = cls.render_profile(
  File \"/Users/{username}/dev/py-venvs/dbtenv/lib/python3.10/site-packages/dbt/config/profile.py\", line 298, in render_profile
    raw_profile_data = cls._get_profile_data(raw_profile, profile_name, target_name)
  File \"/Users/{username}/dev/py-venvs/dbtenv/lib/python3.10/site-packages/dbt/config/profile.py\", line 223, in _get_profile_data
    raise DbtProfileError(msg, result_type=\"invalid_target\")
dbt.exceptions.DbtProfileError: Runtime Error
  The profile '{my-bigquery-profile}' does not have a target named '{{  env_var('DBT_DEV_ENV')  }}'. The valid target names for this profile are:
   - {name1}
   - {name2}
   - {name3}
"
}
```

Doesn't seem relevant here, but just in case: I'm using arm64 (M1 chip).

**Comment by mdesmet** [comment]
Jinja compilation was never supported within the extension. However now with the dbt-osmosis integration, we need to set it up with a target.

The extension might also offer the ability to select a target in the future through UI.

Personally I don't see value of putting profile behind an environment variable, it seems more useful to select targets (maybe based on an environment variable). What's the reasoning behind this environment variable?

cc: @z3z1ma

**Comment by MurugR** [comment]
Hi Michiel, 

Thanks for getting back to me. I've taken your advise and moved schema flexibility down to targets and kept the profile name in dbt_project.yml fixed. Had to refactor a bunch of other framework code to fire off --target instead of --profile, but that was easy. Now everything is working out of the box. 

I'll get my ETL run going in the next hour and don't expect any issues. Will update back if everything is ok in the scheduled EKS environment soon. 

As for your question - no particular reason. It was possible to use environment variables to choose a profile and I opted for that at that time. Just as easy to opt for targets as I've now done. 

It's also ok that at this moment, that the extension takes the default target. I understand this and know how to work around if required. 

Rama

**Comment by MurugR** [comment]
Hi @sdepablos. My profiles.yaml file is slightly different. I have created multiple targets in that file and hardcoded the name of the file in dbt_project.yaml (profile property). When calling, for example, dbt run command I supply --target %ENV_DBT_TARGET%. 

As you can see, I left schema hardcoded in each target and used env_var for host, port, etc. Not sure why I did that - don't remember reading if schema and dbname cannot be parameterized. 

```
profile_name:
  target: prod
  outputs:
    prod:
      type: postgres
      threads: 4
      keepalives_idle: 1
      host: "{{ env_var('ENV_NVG_DB_SVR') }}"
      port: "{{ env_var('ENV_NVG_DB_PORT') | as_number }}"
      user: "{{ env_var('ENV_NVG_DB_USR') }}"
      pass: "{{ env_var('ENV_NVG_DB_PWD') }}"
      dbname: xxx
      schema: public

    dev_rama:
      type: postgres
      threads: 4
      keepalives_idle: 1
      host: "{{ env_var('ENV_NVG_DB_SVR') }}"
      port: "{{ env_var('ENV_NVG_DB_PORT') | as_number }}"
      user: "{{ env_var('ENV_NVG_DB_USR') }}"
      pass: "{{ env_var('ENV_NVG_DB_PWD') }}"
      dbname: xxx
      schema: dbt_rama
```
