### ISSUE TITLE
Running dbt model triggers a infinite run of dbt list

### ISSUE THREAD

**Issue by tiredoak** [innoverio/vscode-dbt-power-user#173]
### Expected behavior

After hitting Run dbt model at the top, the terminal within VSCode should run the model and output the results of that run. Once the model is done running, it should stop.

### Actual behavior

After the model runs, an infinite run of dbt list starts which will not stop unless I kill the terminal window.

### Steps To Reproduce

```
select 
        *
from {{ref('sample_table')}} 
limit 5
```

If I try running this model from the UI with this button

![Screenshot 2022-10-21 at 12 21 15](https://user-images.githubusercontent.com/4021101/197184610-0f637655-d2ec-4fea-8568-47add62dab2a.png)

it starts running a loop of `dbt list` commands.

### Operating System

macOS Monterey 12.4

### dbt version

1.3.0

### dbt Adapter

snowflake

### dbt Power User version

v0.7.9

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
Have you modified the target folder to which your project compiles to?

**Comment by tiredoak** [comment]
I have not. This is my dbt_project.yml 

```

# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'jaffle_shop'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'jaffle_shop'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  jaffle_shop:
    +materialized: table
    staging:
      +materialized: view
```
