### ISSUE TITLE
Excessive alias count indicates a resource exhaustion attack

### ISSUE THREAD

**Issue by BenSimonds** [innoverio/vscode-dbt-power-user#316]
### Expected behavior

Hi I started using your add on. It's great.

When I try to use it in a project with a dbt_project.yml containing nested aliases i end up with errors. Here's a snippet of some config.

```yaml
models:
  # Reusable anchors for tagging models and applying an equivalent BigQuery label.
  meta:
    labels: &commonlabels
      foo: foo
      bar: bar
    frequency: &daily
      +tags: daily
      +labels:
          <<: *commonlabels
          frequency: daily

  warehouse:
    marts:
      sales:
        <<: *daily

# more use of the daily alias follows.
```

### Actual behavior

I get the following error when vscode starts, and am unable to use dbt power user features.

```
Skipping project: could not parse dbt_project_config.yml at '/path/to/dbt_project.yml': ReferenceError: Excessive alias count indicates a resource exhaustion attack.
```

### Steps To Reproduce

Create a dbt project. Use some nested yaml anchors in it.

### Operating System

Mac OS 13.2 (22D49)

### dbt version

1.3.0

### dbt Adapter

dbt-bigquery

### dbt Power User version

v0.11.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!
