### ISSUE TITLE
Documentation editor doesn't support doc function

### ISSUE THREAD

**Issue by HbirdJ** [innoverio/vscode-dbt-power-user#569]
### Expected behavior

The [doc jinja function](https://docs.getdbt.com/reference/dbt-jinja-functions/doc) is not cleanly supported by the documentation editor.

I would expect either one of the following to occur:

- The docs jinja code block shows up in the documentation editor
- Editing and saving the docs block updates the source definition of the doc

### Actual behavior

The documentation editor correctly retrieves the docs block, but overwrites the doc function call when documentation is saved.

### Steps To Reproduce

 `_docs.md`:

```
{% docs time %}
UTC timestamp of the data point. Format is 'YYYY-MM-DD hh:mm:ss[.6_digit_fraction]'
{% enddocs %}
```
 `_models.yml`:
```
  - name: model_name
    description: "model description"
    columns:
      - name: time
        description: '{{ doc("time") }}'
```

After clicking `Save documentation` button, the docs function is overwritten:

 `_models.yml`:
```
  - name: model_name
    description: "model description"
    columns:
      - name: time
        description: UTC timestamp of the data point. Format is 'YYYY-MM-DD
          hh:mm:ss[.6_digit_fraction]'
```

### Log output/Screenshots

The docs block displays the core docs value in the documentation editor.

![image](https://github.com/innoverio/vscode-dbt-power-user/assets/13910021/a7e3a441-3305-4b79-b24c-185b29863b27)

### Operating System

ubuntu 22.04

### dbt version

1.5.4

### dbt Adapter

BigQuery

### dbt Power User version

0.17.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!
